# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleasePoc < Formula
  desc ""
  homepage "https://github.com/nityanandagohain/gorelease_poc"
  version "0.1.14"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/nityanandagohain/gorelease_poc/releases/download/v0.1.14/gorelease_poc_Darwin_x86_64.zip"
    sha256 "a05af4eb2716ecc74602e3f031307a2889031f34073b80f5a0caab5d30d4120c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/nityanandagohain/gorelease_poc/releases/download/v0.1.14/gorelease_poc_Linux_x86_64.zip"
      sha256 "a73629f437cc98d1c0c33e9b4aa357e0ca40ccfedabc407eef25ad92fc37cb5d"
    end
  end

  def install
    bin.install "gorelease_poc"
  end

  test do
    system "#{bin}/gorelease_poc --version"
  end
end
