# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleasePoc < Formula
  desc ""
  homepage "https://github.com/nityanandagohain/gorelease_poc"
  version "0.1.12"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/nityanandagohain/gorelease_poc/releases/download/v0.1.12/gorelease_poc_Darwin_x86_64.zip"
    sha256 "4c767650367ea8a336845e0390aa95307393abf6804722b255dd323f2c874172"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/nityanandagohain/gorelease_poc/releases/download/v0.1.12/gorelease_poc_Linux_x86_64.zip"
      sha256 "476872b1b696d69a54769155cc0729dd9d77560d6350e5b0e9df13f9eaa6606c"
    end
  end

  def install
    bin.install "gorelease_poc"
  end

  test do
    system "#{bin}/gorelease_poc --version"
  end
end

